### PR TITLE
Use NoOp implementation of Logger for package-level functions

### LINKED ISSUE #31: Panic when using package level functions.
If someone used the package level functions, it would crash with a panic, like:
```go
import "github.com/americanas-go/log"

func main() {
  log.Info("Hello World") // this will panic
}
```

There is no documentation pointing that one should instantiate a `Logger` implementation and set it with `log.NewLogger`. **Even if this would be documented, having a package-level function panic because of lack of initialization is unacceptable**.

These functions should be noop or the lib should have a default implementation and rename the `log.NewLogger` to `log.SetGlobalLogger`. Also, with the current `log.NewLogger` is not concurrent-safe and it is impossible to derive what kind of behavior a client in the middle of a log operation would have if another goroutine changed the `Logger` implementation or even set it to `nil`.

Since Go was always an opinionated language and the community follows this approach, I believe that having a production-ready default `Logger` to allow safe and immediate use of the package-level functions is the best way to go. I think that using the `zap` implementation with `INFO` log level and JSON output is a reasonable default.

### PR DESCRIPTION
**Pull request by caiorcferreira**
This PR closes #31.

Although the proposed solution was to use `zap` implementation as default, methods like `WithField(key string, value interface{}) log.Logger` demands that the `zap` package depends on the top-level `log` package, hence there is no way to avoid a circular dependency between the two.

There is no workaround for this because the Go type system is *invariant*. You can read more about this [here](https://eli.thegreenplace.net/2021/go-internals-invariance-and-memory-layout-of-slices/) or test in this playground that I made: https://play.golang.org/p/YpTQKHsjbGq

Therefore, I resort to implement a `NoOp` logger and use it as default. This PR also introduces `log.SetGlobalLogger` and marks `log.NewLogger` as deprecated. I notice that the implementation packages called `log.NewLogger` at the end of the factory functions. I changed to use the new function, however, this should be removed in a v2 since factory functions should not have side effects. Finally, it also makes all package-level functions concurrent-safe.

### CODE REVIEW

File: wrapper.go [hunk 1]
```diff
@@ -1,121 +1,197 @@
...
 
 // NewLogger returns an instance of logger.
+// Deprecated: prefer SetGlobalLogger
 func NewLogger(logger Logger) {
+	mu.Lock()
+	defer mu.Unlock()
+	l = logger
+}
+
+func SetGlobalLogger(logger Logger) {
```
Comment (aleal) [inline wrapper.go:21]: This could be only SetLogger

File: noop.go [hunk 2]
```diff
@@ -0,0 +1,60 @@
+package log
```
Comment (aleal) [inline noop.go:1]: Instead of using a Noop Logger why not use a existing logger like Logrus with the default configs?

File: README.md [hunk 3]
```diff
@@ -85,6 +85,34 @@ func withoutContext() {
...
+	//"github.com/americanas-go/log/contrib/go.uber.org/zap.v1"
+	//"github.com/americanas-go/log/contrib/rs/zerolog.v1"
+	"github.com/americanas-go/log/contrib/sirupsen/logrus.v1"
+)
+
+func main() {
+	//logger := zap.NewLogger()
+	//logger := zerolog.NewLogger()
+	logger := logrus.NewLogger()
+	log.SetGlobalLogger(logger)
```
Comment (aleal) [inline README.md:109]: This call (log.Set...) could be added to NewLogger functions so you dont have do remember to call it every time you instantiate a Logger... what you think?

**Review by aleal — COMMENTED** [review]
I think we could discuss a little more about this implementation, I let some suggestions in the comments

File: noop.go (hunk 2 above)
Comment (dubonzi) [reply noop.go:1]: With the current project structure, this would cause a cyclic dependency problem since the other implementations depend on the `log` package.

File: README.md (hunk 3 above)
Comment (caiorcferreira) [reply README.md:109]: Actually, this already happens, the `log.SetGlobalLogger` is called on the NewLogger functions. As I explained in the PR description, this is a code smell to have side effects inside a constructor/factory. I didn't remove this behavior because it would be a breaking change. Hence, I made the documentation this way in order to promote a better practice to have side effects done in an isolated and explicit way, paving the path to remove this on a v2.

File: noop.go (hunk 2 above)
Comment (caiorcferreira) [reply noop.go:1]: As pointed on by @dubonzi and explained in the PR description, it cannot be done due to a cyclic dependency. Unfortunately, this is not only the project structure fault but a consequence of Go's invariant type system. See the description for more details.

File: wrapper.go (hunk 1 above)
Comment (caiorcferreira) [reply wrapper.go:21]: I choose this name because while `NewLogger` functions produce any number of `Logger` instances, the `SetGlobalLogger` deal if one `Logger` instance in specific, the global one. Hence I believe to be better to make explicitly the responsibility of this function. This is a common design, like [zap's `ReplaceGlobals` functions](https://pkg.go.dev/go.uber.org/zap#ReplaceGlobals).

**Comment by aleal** [comment]
I am sorry, i was attending to a familiar issue... so i stayed away for some days. Changes ok.
